// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bcqezzssotsjummodvit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjcWV6enNzb3RzanVtbW9kdml0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYxMTk2MzcsImV4cCI6MjA5MTY5NTYzN30.rSvoTJzlB5ToLvLAIwBSjdWhSTLM0t37P65-Jg385cw";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);